# Generated by Django 5.1.2 on 2024-11-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='field_order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
